### ISSUE TITLE
GMT Suggestion!

### ISSUE THREAD

**Issue by Arose-Niazi** [Southclaws/samp-geoip#1]
Hey southclaws, small suggestion here do add GetPlayerGMT function.

Output? Either as 
GetPlayerGMT(playerid,Hour,Min);
or HourMin=GetPlayerGMT(playerid); (In Seconds here)

**Comment by Southclaws** [comment]
I assume by GMT you mean time zone, unfortunately the IPHub API doesn't provide this information. It could be looked up elsewhere but that's out of scope for this package.

You could build a package for another API that does provide this information and use this package as a base, the code is rather simple.
